name: Test
on: push
jobs:
  test:
    runs-on: ${{matrix.operating-system}}
    strategy:
      fail-fast: false
      matrix:
        operating-system: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        php-version: ['8.1', '8.2', '8.3', '8.4']
    steps:
    - name: Setup
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{matrix.php-version}}
        tools: phpunit
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Run
      run: phpunit --configuration test/phpunit.xml
